Added function to compare error
CDNA-Technologies/go-utils pull request #12
Opened 2023-04-11 12:46 UTC by punitg8

**- What is this change?**
  Added function to compare error and decide if error are equal or not.

**- Why are we doing?**
  Because it is a common requirement while unit testing in go and requires to right lengthy if else statements each time.
  Eg: `if (tt.wantErr != nil && err != nil && tt.wantErr.Error() != err.Error()) || ((tt.wantErr != nil) != (err != nil))`

**- How was it done before?**
  By manually handling it through writing repetitive if else statement to compare error. 

**- Impact (how efficient is the new flow now)**
  Their will be no need to write those if else manually and a single function call will do the job.

2023-04-11 17:42 UTC, m-aravind11 requested changes

2023-04-11 17:42 UTC, m-aravind11 commented on testing/error.go
> +	return true
```suggestion
	return a.Error() == b.Error()
```

2023-04-11 17:42 UTC, m-aravind11 commented on testing/error_test.go
> +		name string
I feel this is not required. Let's use this only if the test cases aren't very straight forward. Otherwise the description wouldn't add any real value.

2023-04-11 17:42 UTC, m-aravind11 commented on testing/error_test.go
> +	for _, tt := range tests {
```suggestion
	for _, input := range tests {
```
We've used it like this in other tests. Let's keep it consistent.

2023-04-11 17:42 UTC, m-aravind11 commented on testing/error.go
> +	if isANil && isBNil {
```suggestion
	if a == nil && b == nil {
```
Anyways we are doing a comparison, we can as well avoid creating new variables

2023-04-11 17:42 UTC, m-aravind11 commented on testing/error.go
> +	if isANil || isBNil {
```suggestion
	if a == nil || b == nil {
```

2023-04-11 18:02 UTC, punitg8 commented on testing/error.go
> +	return true
done

2023-04-11 18:03 UTC, punitg8 commented on testing/error_test.go
> +		name string
Yes, but now should i keep the test case name in t.Run() as IsErrorEqual ? or leave it as empty

2023-04-11 18:03 UTC, punitg8 commented on testing/error_test.go
> +	for _, tt := range tests {
done

2023-04-11 18:03 UTC, punitg8 commented on testing/error.go
> +	if isANil && isBNil {
yes, done

2023-04-11 18:04 UTC, punitg8 commented on testing/error.go
> +	if isANil || isBNil {
done

2023-04-12 04:19 UTC, m-aravind11 requested changes

2023-04-12 04:19 UTC, m-aravind11 commented on testing/error.go
> +func IsErrorEqual(a, b error) bool {
```suggestion
func IsErrorEqual(wantErr, err error) bool {
```
Can we rename it like this? I feel it'll be more intuitive.

2023-04-12 04:19 UTC, m-aravind11 commented on testing/error_test.go
> +		b    error
```suggestion
		wantErr error
		err     error
```

2023-04-12 04:19 UTC, m-aravind11 commented on testing/error_test.go
> +		t.Run("IsErrorEqual", func(t *testing.T) {
```suggestion
		t.Run(fmt.Sprintf("IsErrorEqual(%v, %v)", wantErr, err), func(t *testing.T) {
```

2023-04-12 04:22 UTC, m-aravind11 commented
Also add a description of the function. Check other functions for reference.

2023-04-12 04:57 UTC, punitg8 commented on testing/error_test.go
> +		name string
Yes, done

2023-04-12 04:58 UTC, punitg8 commented on testing/error.go
> +func IsErrorEqual(a, b error) bool {
Yes, done

2023-04-12 05:07 UTC, m-aravind11 approved these changes

2023-04-12 05:08 UTC, merged